### ISSUE TITLE
Add FOTA logo

### ISSUE THREAD

**Issue by PortaCapena** [sin/energy-calc#42]
[FOTA4Climate-ksiega-znaku.pdf](https://github.com/sin/energy-calc/files/3637828/FOTA4Climate-ksiega-znaku.pdf)
[FOTA4Climate-logo.zip](https://github.com/sin/energy-calc/files/3637872/FOTA4Climate-logo.zip)

**Comment by PortaCapena** [comment]
Lower right corner, not pronounced.

**Comment by sin** [comment]
Related https://github.com/sin/energy-calc/issues/8.
